#Configuration file for player states.
#You can adjust stamina delta (negative value means consumption / positive value means gain) and
#recovery delay (in ticks) of all player states registered in the game.
#To reload the config, use the following command: /paraglider reloadPlayerStates
#
[paraglider]

	[paraglider.ascending]
		# Default: -3.0
		# Range: -Infinity ~ Infinity
		staminaDelta = -3.0
		# Default: 10
		# Range: > 0
		recoveryDelay = 10

	[paraglider.breathing_underwater]
		# Default: 20.0
		# Range: -Infinity ~ Infinity
		staminaDelta = 20.0
		# Default: 0
		# Range: > 0
		recoveryDelay = 0

	[paraglider.creative_flying]
		# Default: 20.0
		# Range: -Infinity ~ Infinity
		staminaDelta = 20.0
		# Default: 0
		# Range: > 0
		recoveryDelay = 0

	[paraglider.elytra_flying]
		# Default: 0.0
		# Range: -Infinity ~ Infinity
		staminaDelta = 0.0
		# Default: 0
		# Range: > 0
		recoveryDelay = 0

	[paraglider.flying]
		# Default: 20.0
		# Range: -Infinity ~ Infinity
		staminaDelta = 20.0
		# Default: 0
		# Range: > 0
		recoveryDelay = 0

	[paraglider.idle]
		# Default: 20.0
		# Range: -Infinity ~ Infinity
		staminaDelta = 20.0
		# Default: 0
		# Range: > 0
		recoveryDelay = 0

	[paraglider.midair]
		# Default: 0.0
		# Range: -Infinity ~ Infinity
		staminaDelta = 0.0
		# Default: 0
		# Range: > 0
		recoveryDelay = 0

	[paraglider.on_vehicle]
		# Default: 20.0
		# Range: -Infinity ~ Infinity
		staminaDelta = 20.0
		# Default: 0
		# Range: > 0
		recoveryDelay = 0

	[paraglider.panic_paragliding]
		# Default: -3.0
		# Range: -Infinity ~ Infinity
		staminaDelta = -3.0
		# Default: 10
		# Range: > 0
		recoveryDelay = 10

	[paraglider.paragliding]
		# Default: -3.0
		# Range: -Infinity ~ Infinity
		staminaDelta = -3.0
		# Default: 10
		# Range: > 0
		recoveryDelay = 10

	[paraglider.running]
		# Default: -10.0
		# Range: -Infinity ~ Infinity
		staminaDelta = -10.0
		# Default: 10
		# Range: > 0
		recoveryDelay = 10

	[paraglider.swimming]
		# Default: -6.0
		# Range: -Infinity ~ Infinity
		staminaDelta = -6.0
		# Default: 10
		# Range: > 0
		recoveryDelay = 10

	[paraglider.underwater]
		# Default: 3.0
		# Range: -Infinity ~ Infinity
		staminaDelta = 3.0
		# Default: 0
		# Range: > 0
		recoveryDelay = 0
