#If true, wind sources will generate updrafts that interact with Paraglider.
#Wind sources and strength (i.e. height) of the updraft created can be adjusted with datapacks.
#See online docs for more information: (work in progress)
updraft = true
#Multiplier to horizontal movement speed while paragliding.
#Value of 0.5 means 50% of the speed, 2.0 means two times the speed and so forth.
# Default: 1.0
# Range: 0.2 ~ 10.0
paraglidingSpeed = 1.0
#Durability of Paragliders. Set to zero to disable durability.
# Default: 0
# Range: > 0
paragliderDurability = 0
#Configurable option for Towers of the Wild compat feature. Can be ignored if Towers of the Wild is not installed.
#DEFAULT: Default option, spawn Deku Leaf in ocean tower chests and Paraglider in normal tower chests
#DISABLE: Don't spawn anything
#PARAGLIDER_ONLY: Spawn paraglider in both ocean and normal tower chests
#DEKU_LEAF_ONLY: Spawn deku leaf in both ocean and normal tower chests, like a boss
#Allowed Values: DEFAULT, DISABLE, PARAGLIDER_ONLY, DEKU_LEAF_ONLY
paragliderInTowersOfTheWild = "DEFAULT"

[spiritOrbs]
	#If true, Wither will drop heart container(stamina vessel if heart container is disabled) upon death.
	enderDragonDropsVessel = true
	#If true, Elder Guardian will drop a Spirit Orb upon death.
	raidGivesVessel = true
	#Amount of Spirit Orbs dropped from spawners. Fractional values are treated as a chanced drop, in addition to whole values which is guaranteed to drop.
	# Default: 1.0
	# Range: 0.0 ~ 64.0
	spawnerSpiritOrbDrops = 1.0
	#Amount of Spirit Orbs dropped from completing trial. Fractional values are treated as a chanced drop, in addition to whole values which is guaranteed to drop.
	# Default: 2.0
	# Range: 0.0 ~ 64.0
	trialSpiritOrbDrops = 2.0
	#Amount of Spirit Orbs dropped from completing ominous trial. Fractional values are treated as a chanced drop, in addition to whole values which is guaranteed to drop.
	# Default: 4.0
	# Range: 0.0 ~ 64.0
	ominousTrialSpiritOrbDrops = 4.0
	#If true, various types of chest will have chances of having Spirit Orbs inside.
	#Does not change contents of already generated chests.
	spiritOrbLoots = true

[vessels]
	#Starting health points measured in number of hearts.
	# Default: 10
	# Range: 1 ~ 512
	startingHearts = 10
	#Maximum amount of Heart Containers one player can consume.
	#Do note that the maximum health point is capped at value of 1024 (or 512 hearts) by Minecraft's default
	#attribute system; without modifying these limits, Heart Containers won't give you extra hearts beyond that.
	# Default: 20
	# Range: 0 ~ 512
	maxHeartContainers = 20
	#Amount of stamina players start with. One full stamina wheel is equivalent to 1000 stamina.
	# Default: 1000
	# Range: > 0
	startingStamina = 1000
	#Maximum amount of Stamina Vessels one player can consume. Higher value = higher maximum stamina.
	# Default: 10
	# Range: > 0
	maxStaminaVessels = 10
	#Stamina increase per vessel. One full stamina wheel is equivalent to 1000 stamina.
	# Default: 200
	# Range: > 0
	staminaIncreasePerVessel = 200

[stamina]
	#Paragliding will consume stamina. Run /paraglider reloadPlayerStates after change.
	paraglidingConsumesStamina = true
	#Certain non-paragliding actions, such as running and swimming, will consume stamina. Run /paraglider reloadPlayerStates after change.
	runningAndSwimmingConsumesStamina = false
